name: ocido
channels:
  - http://s0hrep0001h.cbsp.nl/Anaconda/pkgs/free/
  - http://s0hrep0001h.cbsp.nl/Anaconda/pkgs/main/
  - nodefaults
dependencies:
  - python=3.7.7
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - babel=2.6.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - click=7.0
  - colorama=0.4.3
  - flask=1.0.2
  - flask-babel=0.12.2
  - importlib_metadata=1.5.0
  - itsdangerous=1.1.0
  - jinja2=2.11.1
  - jsonschema=3.2.0
  - markupsafe=1.1.1
  - more-itertools=8.2.0
  - openssl=1.1.1f
  - packaging=20.1
  - pip=20.0.2
  - pluggy=0.13.1
  - py=1.8.1
  - pyparsing=2.4.6
  - pyrsistent=0.15.7
  - pytest=5.3.5
  - pytz=2019.3
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - wcwidth=0.1.8
  - werkzeug=1.0.0
  - wheel=0.34.2
  - zipp=2.2.0
  - zlib=1.2.11

