from unittest import TestCase


class Controle(TestCase):

    def test_geef_codechecklijst(self):
        from applicatie.logic.controles import geef_codechecklijst

        codelijst = {'taakveld': {'codelijst': [{'code': '0.', 'omschrijving': 'BESTUUR EN ONDERSTEUNING',
                                                 'subcodes': [{'code': '0.1', 'omschrijving': 'Bestuur'},
                                                              {'code': '0.10', 'omschrijving': 'Mutaties reserves'},
                                                              {'code': '0.11',
                                                               'omschrijving': 'Resultaat van de rekening van baten en lasten'},
                                                              {'code': '0.2', 'omschrijving': 'Burgerzaken'},
                                                              {'code': '0.3',
                                                               'omschrijving': 'Beheer overige gebouwen en gronden'},
                                                              {'code': '0.4', 'omschrijving': 'Overhead'},
                                                              {'code': '0.5', 'omschrijving': 'Treasury'},
                                                              {'code': '0.61', 'omschrijving': 'OZB woningen'},
                                                              {'code': '0.62', 'omschrijving': 'OZB niet-woningen'},
                                                              {'code': '0.63', 'omschrijving': 'Parkeerbelasting'},
                                                              {'code': '0.64', 'omschrijving': 'Belastingen overig'},
                                                              {'code': '0.7',
                                                               'omschrijving': 'Algemene uitkeringen en overige uitkeringen gemeentefonds'},
                                                              {'code': '0.8', 'omschrijving': 'Overige baten en lasten'},
                                                              {'code': '0.9',
                                                               'omschrijving': 'Vennootschapsbelasting (VpB)'}]},
                                                {'code': '1.', 'omschrijving': 'VEILIGHEID', 'subcodes': [
                                                    {'code': '1.1', 'omschrijving': 'Crisisbeheersing en brandweer'},
                                                    {'code': '1.2', 'omschrijving': 'Openbare orde en veiligheid'}]},
                                                {'code': '2.', 'omschrijving': 'VERKEER, VERVOER EN WATERSTAAT',
                                                 'subcodes': [{'code': '2.1', 'omschrijving': 'Verkeer en vervoer'},
                                                              {'code': '2.2', 'omschrijving': 'Parkeren'},
                                                              {'code': '2.3', 'omschrijving': 'Recreatieve havens'},
                                                              {'code': '2.4',
                                                               'omschrijving': 'Economische havens en waterwegen'},
                                                              {'code': '2.5', 'omschrijving': 'Openbaar vervoer'}]},
                                                {'code': '3.', 'omschrijving': 'ECONOMIE', 'subcodes': [
                                                    {'code': '3.1', 'omschrijving': 'Economische ontwikkeling'},
                                                    {'code': '3.2', 'omschrijving': 'Fysieke bedrijfsinfrastructuur'},
                                                    {'code': '3.3',
                                                     'omschrijving': 'Bedrijvenloket en bedrijfsregelingen'},
                                                    {'code': '3.4', 'omschrijving': 'Economische promotie'}]},
                                                {'code': '4.', 'omschrijving': 'ONDERWIJS',
                                                 'subcodes': [{'code': '4.1', 'omschrijving': 'Openbaar basisonderwijs'},
                                                              {'code': '4.2', 'omschrijving': 'Onderwijshuisvesting'},
                                                              {'code': '4.3',
                                                               'omschrijving': 'Onderwijsbeleid en leerlingzaken'}]},
                                                {'code': '5.', 'omschrijving': 'SPORT, CULTUUR EN RECREATIE',
                                                 'subcodes': [
                                                     {'code': '5.1', 'omschrijving': 'Sportbeleid en activering'},
                                                     {'code': '5.2', 'omschrijving': 'Sportaccommodaties'},
                                                     {'code': '5.3',
                                                      'omschrijving': 'Cultuurpresentatie, cultuurproductie en cultuurparticipatie'},
                                                     {'code': '5.4', 'omschrijving': 'Musea'},
                                                     {'code': '5.5', 'omschrijving': 'Cultureel erfgoed'},
                                                     {'code': '5.6', 'omschrijving': 'Media'}, {'code': '5.7',
                                                                                               'omschrijving': 'Openbaar groen en (openlucht) recreatie'}]},
                                                {'code': '6.', 'omschrijving': 'SOCIAAL DOMEIN', 'subcodes': [
                                                    {'code': '6.1', 'omschrijving': 'Samenkracht en burgerparticipatie'},
                                                    {'code': '6.2', 'omschrijving': 'Wijkteams'},
                                                    {'code': '6.3', 'omschrijving': 'Inkomensregelingen'},
                                                    {'code': '6.4', 'omschrijving': 'Begeleide participatie'},
                                                    {'code': '6.5', 'omschrijving': 'Arbeidsparticipatie'},
                                                    {'code': '6.6', 'omschrijving': 'Maatwerkvoorziening WMO'},
                                                    {'code': '6.71', 'omschrijving': 'Maatwerkdienstverlening 18+'},
                                                    {'code': '6.72', 'omschrijving': 'Maatwerkdienstverlening 18-'},
                                                    {'code': '6.81', 'omschrijving': 'GeÃ«scaleerde zorg 18+'},
                                                    {'code': '6.82', 'omschrijving': 'GeÃ«scaleerde zorg 18-'}]},
                                                {'code': '7.', 'omschrijving': 'VOLKSGEZONDHEID EN MILIEU',
                                                 'subcodes': [{'code': '7.1', 'omschrijving': 'Volksgezondheid'},
                                                              {'code': '7.2', 'omschrijving': 'Riolering'},
                                                              {'code': '7.3', 'omschrijving': 'Afval'},
                                                              {'code': '7.4', 'omschrijving': 'Milieubeheer'},
                                                              {'code': '7.5',
                                                               'omschrijving': 'Begraafplaatsen en crematoria'}]},
                                                {'code': '8.',
                                                 'omschrijving': 'VOLKSHUISVESTING, RUIMTELIJKE ORDENING EN STEDELIJKE VERNIEUWING',
                                                 'subcodes': [{'code': '8.1', 'omschrijving': 'Ruimtelijke ordening'},
                                                              {'code': '8.2',
                                                               'omschrijving': 'Grondexploitatie (niet-bedrijventerreinen)'},
                                                              {'code': '8.3', 'omschrijving': 'Wonen en bouwen'}]}]},
                     'balanscode': {'codelijst': [{'code': 'A1', 'omschrijving': 'Vaste Activa', 'subcodes': [
                         {'code': 'A111',
                          'omschrijving': 'Immatriele vaste activa: Kosten verbonden aan sluiten geldlening en saldo agio/disagio'},
                         {'code': 'A112',
                          'omschrijving': 'Immatriele vaste activa: Kosten onderzoek en ontwikkeling voor een bepaald actief'},
                         {'code': 'A113',
                          'omschrijving': 'Immatriele vaste activa: Bijdragen aan activa in eigendom van derden'},
                         {'code': 'A121', 'omschrijving': 'Matriele vaste activa: Gronden en terreinen'},
                         {'code': 'A122', 'omschrijving': 'Matriele vaste activa: Woonruimten'},
                         {'code': 'A123', 'omschrijving': 'Matriele vaste activa: Bedrijfsgebouwen'}, {'code': 'A124',
                                                                                                      'omschrijving': 'Matriele vaste activa: Grond-, weg- en waterbouwkundige werken'},
                         {'code': 'A125', 'omschrijving': 'Matriele vaste activa: Vervoermiddelen'},
                         {'code': 'A126', 'omschrijving': 'Matriele vaste activa: Machines, apparaten en installaties'},
                         {'code': 'A129', 'omschrijving': 'Matriele vaste activa: Overig'}, {'code': 'A1311',
                                                                                            'omschrijving': 'Financiele vaste activa: Kapitaalverstrekking aan deelnemingen'},
                         {'code': 'A1312',
                          'omschrijving': 'Financiele vaste activa: Kapitaalverstrekking aan gemeenschappelijke regelingen'},
                         {'code': 'A1313',
                          'omschrijving': 'Financiele vaste activa: Kapitaalverstrekking aan overige verbonden partijen'},
                         {'code': 'A1321',
                          'omschrijving': 'Financiele vaste activa: Leningen aan woningbouwcorporaties'},
                         {'code': 'A1322', 'omschrijving': 'Financiele vaste activa: Leningen aan deelnemingen'},
                         {'code': 'A1323',
                          'omschrijving': 'Financiele vaste activa: Leningen aan overige verbonden partijen'},
                         {'code': 'A1331a',
                          'omschrijving': 'Financiele vaste activa: Leningen aan openbare lichamen (art. 1a Wet Fido)'},
                         {'code': 'A1331b', 'omschrijving': 'Financiele vaste activa: Overige langlopende leningen'},
                         {'code': 'A1332a',
                          'omschrijving': 'Financiele vaste activa: Uitzettingen in s Rijks schatkist met een looptijd = 1 jaar'},
                         {'code': 'A1332b',
                          'omschrijving': 'Financiele vaste activa: Uitzettingen in de vorm van Nederlands schuldpapier met een looptijd = 1 jaar'},
                         {'code': 'A1332c',
                          'omschrijving': 'Financiele vaste activa: Overige uitzettingen met een looptijd = 1 jaar'}]},
                                                  {'code': 'A2', 'omschrijving': 'Vlottende Activa', 'subcodes': [
                                                      {'code': 'A212',
                                                       'omschrijving': 'Voorraden: Overige grond- en hulpstoffen'},
                                                      {'code': 'A213',
                                                       'omschrijving': 'Voorraden: Onderhanden werk (incl. bouwgronden in exploitatie)'},
                                                      {'code': 'A214',
                                                       'omschrijving': 'Voorraden: Gereed product en handelsgoederen'},
                                                      {'code': 'A215', 'omschrijving': 'Voorraden: Vooruitbetalingen'},
                                                      {'code': 'A221',
                                                       'omschrijving': 'Uitzettingen: Vorderingen op openbare lichamen'},
                                                      {'code': 'A222a',
                                                       'omschrijving': 'Uitzettingen: Verstrekte kasgeldleningen aan openbare lichamen (art. 1a Wet Fido)'},
                                                      {'code': 'A222b',
                                                       'omschrijving': 'Uitzettingen: Overige verstrekte kasgeldleningen'},
                                                      {'code': 'A223a',
                                                       'omschrijving': 'Uitzettingen: Rekening courant verhouding met het Rijk'},
                                                      {'code': 'A223b',
                                                       'omschrijving': 'Uitzettingen: Rekening courant verhoudingen overige niet-Financiele instellingen'},
                                                      {'code': 'A224',
                                                       'omschrijving': 'Uitzettingen: Overige vorderingen'},
                                                      {'code': 'A225a',
                                                       'omschrijving': 'Uitzettingen: Uitzettingen in s Rijks schatkist met een looptijd < 1 jaar'},
                                                      {'code': 'A225b',
                                                       'omschrijving': 'Uitzettingen: Uitzettingen in de vorm van Nederlands schuldpapier met een looptijd < 1 jaar'},
                                                      {'code': 'A225c',
                                                       'omschrijving': 'Uitzettingen: Overige uitzettingen met een looptijd < 1 jaar'},
                                                      {'code': 'A23',
                                                       'omschrijving': 'Liquide middelen (kas- en banksaldi)'},
                                                      {'code': 'A29a',
                                                       'omschrijving': 'Overlopende activa: Nog te ontvangen bijdragen van de EU'},
                                                      {'code': 'A29b',
                                                       'omschrijving': 'Overlopende activa: Nog te ontvangen bijdragen van het Rijk'},
                                                      {'code': 'A29c',
                                                       'omschrijving': 'Overlopende activa: Nog te ontvangen bijdragen van overige overheid'},
                                                      {'code': 'A29d',
                                                       'omschrijving': 'Overlopende activa: Overige overlopende activa'}]},
                                                  {'code': 'P1', 'omschrijving': 'Vaste Passiva', 'subcodes': [
                                                      {'code': 'P111',
                                                       'omschrijving': 'Eigen vermogen: Algemene reserve'},
                                                      {'code': 'P112',
                                                       'omschrijving': 'Eigen vermogen: Bestemmingsreserves'},
                                                      {'code': 'P114',
                                                       'omschrijving': 'Eigen vermogen: Saldo van rekening'},
                                                      {'code': 'P12', 'omschrijving': 'Voorzieningen'}, {'code': 'P131',
                                                                                                        'omschrijving': 'Vaste schuld: Obligatieleningen'},
                                                      {'code': 'P132',
                                                       'omschrijving': 'Vaste schuld: Onderhandse leningen van binnenlandse pensioenfondsen en verzekeraars'},
                                                      {'code': 'P133',
                                                       'omschrijving': 'Vaste schuld: Onderhandse leningen van binnenlandse banken en overige Financiele instellingen'},
                                                      {'code': 'P134',
                                                       'omschrijving': 'Vaste schuld: Onderhandse leningen van binnenlandse bedrijven'},
                                                      {'code': 'P135a',
                                                       'omschrijving': 'Vaste schuld: Onderhandse leningen van openbare lichamen (art. 1a Wet Fido)'},
                                                      {'code': 'P135b',
                                                       'omschrijving': 'Vaste schuld: Onderhandse leningen van overige binnenlandse sectoren'},
                                                      {'code': 'P136',
                                                       'omschrijving': 'Vaste schuld: Onderhandse leningen van buitenlandse instellingen'},
                                                      {'code': 'P137',
                                                       'omschrijving': 'Vaste schuld: Door derden belegde gelden'},
                                                      {'code': 'P138', 'omschrijving': 'Vaste schuld: Waarborgsommen'},
                                                      {'code': 'P139', 'omschrijving': 'Renteswaps en derivaten'}]},
                                                  {'code': 'P2', 'omschrijving': 'Vlottende Passiva', 'subcodes': [
                                                      {'code': 'P211a',
                                                       'omschrijving': 'Vlottende schuld: Kasgeldleningen van openbare lichamen (art. 1a Wet Fido)'},
                                                      {'code': 'P211b',
                                                       'omschrijving': 'Vlottende schuld: Overige kasgeldleningen'},
                                                      {'code': 'P212', 'omschrijving': 'Vlottende schuld: Banksaldi'},
                                                      {'code': 'P213',
                                                       'omschrijving': 'Vlottende schuld: Overige vlottende schulden'},
                                                      {'code': 'P29a',
                                                       'omschrijving': 'Overlopende passiva: Vooruit ontvangen bijdragen van de EU'},
                                                      {'code': 'P29b',
                                                       'omschrijving': 'Overlopende passiva: Vooruit ontvangen bijdragen van het Rijk'},
                                                      {'code': 'P29c',
                                                       'omschrijving': 'Overlopende passiva: Vooruit ontvangen bijdragen van overige overheid'},
                                                      {'code': 'P29d',
                                                       'omschrijving': 'Overlopende passiva: Overige overlopende passiva'}]}]},
                     'standper': {'codelijst': [{'code': '1 januari', 'omschrijving': 'begindatum'},
                                                {'code': 'ultimo', 'omschrijving': 'einddatum'}]}, 'categorie_lasten': {
                'codelijst': [{'code': 'Lopende Rekening',
                               'subcodes': [{'code': '1.1', 'omschrijving': 'Salarissen en sociale lasten'},
                                            {'code': '2.1', 'omschrijving': 'Belastingen'},
                                            {'code': '3.1', 'omschrijving': 'Grond'},
                                            {'code': '3.2', 'omschrijving': 'Duurzame goederen'},
                                            {'code': '3.3', 'omschrijving': 'Pachten'},
                                            {'code': '3.4.1', 'omschrijving': 'Sociale uitkeringen in natura'},
                                            {'code': '3.5.1', 'omschrijving': 'Ingeleend personeel'},
                                            {'code': '3.8', 'omschrijving': 'Overige goederen en diensten'},
                                            {'code': '4.1.1', 'omschrijving': 'Sociale uitkeringen in geld'},
                                            {'code': '4.2', 'omschrijving': 'Subsidies'},
                                            {'code': '4.3.1', 'omschrijving': 'Inkomensoverdrachten - Rijk'},
                                            {'code': '4.3.2', 'omschrijving': 'Inkomensoverdrachten - gemeenten'},
                                            {'code': '4.3.3',
                                             'omschrijving': 'Inkomensoverdrachten - gemeenschappelijke regelingen'},
                                            {'code': '4.3.4', 'omschrijving': 'Inkomensoverdrachten - provincies'},
                                            {'code': '4.3.5', 'omschrijving': 'Inkomensoverdrachten - waterschappen'},
                                            {'code': '4.3.6',
                                             'omschrijving': 'Inkomensoverdrachten - overige overheden'},
                                            {'code': '4.3.7', 'omschrijving': 'Inkomensoverdrachten - Europese Unie'},
                                            {'code': '4.3.8',
                                             'omschrijving': 'Inkomensoverdrachten - overige instellingen en personen'},
                                            {'code': '4.3.9', 'omschrijving': 'Inkomensoverdrachten - onverdeeld'},
                                            {'code': '4.4.1', 'omschrijving': 'Kapitaaloverdrachten - Rijk'},
                                            {'code': '4.4.2', 'omschrijving': 'Kapitaaloverdrachten - gemeenten'},
                                            {'code': '4.4.3',
                                             'omschrijving': 'Kapitaaloverdrachten - gemeenschappelijke regelingen'},
                                            {'code': '4.4.4', 'omschrijving': 'Kapitaaloverdrachten - provincies'},
                                            {'code': '4.4.5', 'omschrijving': 'Kapitaaloverdrachten - waterschappen'},
                                            {'code': '4.4.6',
                                             'omschrijving': 'Kapitaaloverdrachten - overige overheden'},
                                            {'code': '4.4.7', 'omschrijving': 'Kapitaaloverdrachten - Europese Unie'},
                                            {'code': '4.4.8',
                                             'omschrijving': 'Kapitaaloverdrachten - overige instellingen en personen'},
                                            {'code': '4.4.9', 'omschrijving': 'Kapitaaloverdrachten - onverdeeld'},
                                            {'code': '5.1', 'omschrijving': 'Rente'}]}, {'code': 'Financiele Rekening',
                                                                                        'subcodes': [{'code': '6.1',
                                                                                                      'omschrijving': 'Financiele transacties'}]},
                              {'code': 'Interne Verrekeningen',
                               'subcodes': [{'code': '7.1', 'omschrijving': 'Mutatie reserves'},
                                            {'code': '7.2', 'omschrijving': 'Mutatie voorzieningen'},
                                            {'code': '7.3', 'omschrijving': 'Afschrijvingen'},
                                            {'code': '7.4', 'omschrijving': 'Toegerekende reeele en bespaarde rente'},
                                            {'code': '7.5', 'omschrijving': 'Overige verrekeningen'}]}]},
                     'categorie_baten': {'codelijst': [{'code': 'Lopende Rekening', 'subcodes': [
                         {'code': '2.2.1', 'omschrijving': 'Belastingen op producenten'},
                         {'code': '2.2.2', 'omschrijving': 'Belastingen op huishoudens'},
                         {'code': '3.1', 'omschrijving': 'Grond'}, {'code': '3.2', 'omschrijving': 'Duurzame goederen'},
                         {'code': '3.3', 'omschrijving': 'Pachten'},
                         {'code': '3.4.2', 'omschrijving': 'Eigen bijdragen en verhaal sociale uitkeringen in natura'},
                         {'code': '3.5.2', 'omschrijving': 'Uitgeleend personeel'},
                         {'code': '3.6', 'omschrijving': 'Huren'},
                         {'code': '3.7', 'omschrijving': 'Leges en andere rechten'},
                         {'code': '3.8', 'omschrijving': 'Overige goederen en diensten'},
                         {'code': '4.1.2', 'omschrijving': 'Verhaal sociale uitkeringen in geld'},
                         {'code': '4.3.1', 'omschrijving': 'Inkomensoverdrachten - Rijk'},
                         {'code': '4.3.2', 'omschrijving': 'Inkomensoverdrachten - gemeenten'},
                         {'code': '4.3.3', 'omschrijving': 'Inkomensoverdrachten - gemeenschappelijke regelingen'},
                         {'code': '4.3.4', 'omschrijving': 'Inkomensoverdrachten - provincies'},
                         {'code': '4.3.5', 'omschrijving': 'Inkomensoverdrachten - waterschappen'},
                         {'code': '4.3.6', 'omschrijving': 'Inkomensoverdrachten - overige overheden'},
                         {'code': '4.3.7', 'omschrijving': 'Inkomensoverdrachten - Europese Unie'},
                         {'code': '4.3.8', 'omschrijving': 'Inkomensoverdrachten - overige instellingen en personen'},
                         {'code': '4.3.9', 'omschrijving': 'Inkomensoverdrachten - onverdeeld'},
                         {'code': '4.4.1', 'omschrijving': 'Kapitaaloverdrachten - Rijk'},
                         {'code': '4.4.2', 'omschrijving': 'Kapitaaloverdrachten - gemeenten'},
                         {'code': '4.4.3', 'omschrijving': 'Kapitaaloverdrachten - gemeenschappelijke regelingen'},
                         {'code': '4.4.4', 'omschrijving': 'Kapitaaloverdrachten - provincies'},
                         {'code': '4.4.5', 'omschrijving': 'Kapitaaloverdrachten - waterschappen'},
                         {'code': '4.4.6', 'omschrijving': 'Kapitaaloverdrachten - overige overheden'},
                         {'code': '4.4.7', 'omschrijving': 'Kapitaaloverdrachten - Europese Unie'},
                         {'code': '4.4.8', 'omschrijving': 'Kapitaaloverdrachten - overige instellingen en personen'},
                         {'code': '4.4.9', 'omschrijving': 'Kapitaaloverdrachten - onverdeeld'},
                         {'code': '5.1', 'omschrijving': 'Rente'},
                         {'code': '5.2', 'omschrijving': 'Dividenden en winsten'}]}, {'code': 'Financiele Rekening',
                                                                                     'subcodes': [{'code': '6.1',
                                                                                                   'omschrijving': 'Financiele transacties'}]},
                                                       {'code': 'Interne Verrekeningen',
                                                        'subcodes': [{'code': '7.1', 'omschrijving': 'Mutatie reserves'},
                                                                     {'code': '7.2',
                                                                      'omschrijving': 'Mutatie voorzieningen'},
                                                                     {'code': '7.3', 'omschrijving': 'Afschrijvingen'},
                                                                     {'code': '7.4',
                                                                      'omschrijving': 'Toegerekende reeele en bespaarde rente'},
                                                                     {'code': '7.5',
                                                                      'omschrijving': 'Overige verrekeningen'}]}]},
                     'dimensies': {'codelijst': [{'code': 'dimensies_lasten', 'rekeningsoort': 'lasten',
                                                  'omschrijving': 'dimensies voor rekeningsoort lasten', 'subcodes': [
                             {'code': 'dimensie_1', 'sleutelnaam': 'categorie', 'codelijst': 'categorie_lasten',
                              'omschrijving': 'kolomkoppen lasten tabel'},
                             {'code': 'dimensie_2', 'sleutelnaam': 'taakveld', 'codelijst': 'taakveld',
                              'omschrijving': 'rijkoppen lasten tabel'}]},
                                                 {'code': 'dimensies_baten', 'rekeningsoort': 'baten',
                                                  'omschrijving': 'dimensies voor rekeningsoort baten', 'subcodes': [
                                                     {'code': 'dimensie_1', 'sleutelnaam': 'categorie',
                                                      'codelijst': 'categorie_baten',
                                                      'omschrijving': 'kolomkoppen baten tabel'},
                                                     {'code': 'dimensie_2', 'sleutelnaam': 'taakveld',
                                                      'codelijst': 'taakveld',
                                                      'omschrijving': 'rijkoppen baten tabel'}]},
                                                 {'code': 'dimensies_balans_lasten', 'rekeningsoort': 'balans_lasten',
                                                  'omschrijving': 'dimensies voor rekeningsoort balans_lasten',
                                                  'subcodes': [{'code': 'dimensie_1', 'sleutelnaam': 'categorie',
                                                                'codelijst': 'categorie_lasten',
                                                                'omschrijving': 'kolomkoppen balans_lasten tabel'},
                                                               {'code': 'dimensie_2', 'sleutelnaam': 'balanscode',
                                                                'codelijst': 'balanscode',
                                                                'omschrijving': 'rijkoppen balans_lasten tabel'}]},
                                                 {'code': 'dimensies_balans_baten', 'rekeningsoort': 'balans_baten',
                                                  'omschrijving': 'dimensies voor rekeningsoort balans_baten',
                                                  'subcodes': [{'code': 'dimensie_1', 'sleutelnaam': 'categorie',
                                                                'codelijst': 'categorie_baten',
                                                                'omschrijving': 'kolomkoppen balans_baten tabel'},
                                                               {'code': 'dimensie_2', 'sleutelnaam': 'balanscode',
                                                                'codelijst': 'balanscode',
                                                                'omschrijving': 'rijkoppen balans_baten tabel'}]},
                                                 {'code': 'dimensies_balans_standen', 'rekeningsoort': 'balans_standen',
                                                  'omschrijving': 'dimensies voor rekeningsoort balans_standen',
                                                  'subcodes': [{'code': 'dimensie_1', 'sleutelnaam': 'standper',
                                                                'codelijst': 'standper',
                                                                'omschrijving': 'kolomkoppen balans_standen tabel'},
                                                               {'code': 'dimensie_2', 'sleutelnaam': 'balanscode',
                                                                'codelijst': 'balanscode',
                                                                'omschrijving': 'rijkoppen balans_standen tabel'}]}]}}

        result = geef_codechecklijst(codelijst)

        exp_result = {'taakveld': ['0.', 'BESTUUR EN ONDERSTEUNING', 1, '', '0.1', 'Bestuur', 2, '0.', '0.10',
                                   'Mutaties reserves', 2, '0.', '0.11',
                                   'Resultaat van de rekening van baten en lasten', 2, '0.', '0.2', 'Burgerzaken', 2,
                                   '0.', '0.3', 'Beheer overige gebouwen en gronden', 2, '0.', '0.4', 'Overhead', 2,
                                   '0.', '0.5', 'Treasury', 2, '0.', '0.61', 'OZB woningen', 2, '0.', '0.62',
                                   'OZB niet-woningen', 2, '0.', '0.63', 'Parkeerbelasting', 2, '0.', '0.64',
                                   'Belastingen overig', 2, '0.', '0.7',
                                   'Algemene uitkeringen en overige uitkeringen gemeentefonds', 2, '0.', '0.8',
                                   'Overige baten en lasten', 2, '0.', '0.9', 'Vennootschapsbelasting (VpB)', 2, '0.',
                                   '1.', 'VEILIGHEID', 1, '', '1.1', 'Crisisbeheersing en brandweer', 2, '1.', '1.2',
                                   'Openbare orde en veiligheid', 2, '1.', '2.', 'VERKEER, VERVOER EN WATERSTAAT', 1,
                                   '', '2.1', 'Verkeer en vervoer', 2, '2.', '2.2', 'Parkeren', 2, '2.', '2.3',
                                   'Recreatieve havens', 2, '2.', '2.4', 'Economische havens en waterwegen', 2, '2.',
                                   '2.5', 'Openbaar vervoer', 2, '2.', '3.', 'ECONOMIE', 1, '', '3.1',
                                   'Economische ontwikkeling', 2, '3.', '3.2', 'Fysieke bedrijfsinfrastructuur', 2,
                                   '3.', '3.3', 'Bedrijvenloket en bedrijfsregelingen', 2, '3.', '3.4',
                                   'Economische promotie', 2, '3.', '4.', 'ONDERWIJS', 1, '', '4.1',
                                   'Openbaar basisonderwijs', 2, '4.', '4.2', 'Onderwijshuisvesting', 2, '4.', '4.3',
                                   'Onderwijsbeleid en leerlingzaken', 2, '4.', '5.', 'SPORT, CULTUUR EN RECREATIE', 1,
                                   '', '5.1', 'Sportbeleid en activering', 2, '5.', '5.2', 'Sportaccommodaties', 2,
                                   '5.', '5.3', 'Cultuurpresentatie, cultuurproductie en cultuurparticipatie', 2, '5.',
                                   '5.4', 'Musea', 2, '5.', '5.5', 'Cultureel erfgoed', 2, '5.', '5.6', 'Media', 2,
                                   '5.', '5.7', 'Openbaar groen en (openlucht) recreatie', 2, '5.', '6.',
                                   'SOCIAAL DOMEIN', 1, '', '6.1', 'Samenkracht en burgerparticipatie', 2, '6.', '6.2',
                                   'Wijkteams', 2, '6.', '6.3', 'Inkomensregelingen', 2, '6.', '6.4',
                                   'Begeleide participatie', 2, '6.', '6.5', 'Arbeidsparticipatie', 2, '6.', '6.6',
                                   'Maatwerkvoorziening WMO', 2, '6.', '6.71', 'Maatwerkdienstverlening 18+', 2, '6.',
                                   '6.72', 'Maatwerkdienstverlening 18-', 2, '6.', '6.81', 'GeÃ«scaleerde zorg 18+', 2,
                                   '6.', '6.82', 'GeÃ«scaleerde zorg 18-', 2, '6.', '7.', 'VOLKSGEZONDHEID EN MILIEU',
                                   1, '', '7.1', 'Volksgezondheid', 2, '7.', '7.2', 'Riolering', 2, '7.', '7.3',
                                   'Afval', 2, '7.', '7.4', 'Milieubeheer', 2, '7.', '7.5',
                                   'Begraafplaatsen en crematoria', 2, '7.', '8.',
                                   'VOLKSHUISVESTING, RUIMTELIJKE ORDENING EN STEDELIJKE VERNIEUWING', 1, '', '8.1',
                                   'Ruimtelijke ordening', 2, '8.', '8.2', 'Grondexploitatie (niet-bedrijventerreinen)',
                                   2, '8.', '8.3', 'Wonen en bouwen', 2, '8.'],
                      'balanscode': ['A1', 'Vaste Activa', 1, '', 'A111',
                                     'Immatriele vaste activa: Kosten verbonden aan sluiten geldlening en saldo agio/disagio',
                                     2, 'A1', 'A112',
                                     'Immatriele vaste activa: Kosten onderzoek en ontwikkeling voor een bepaald actief',
                                     2, 'A1', 'A113',
                                     'Immatriele vaste activa: Bijdragen aan activa in eigendom van derden', 2, 'A1',
                                     'A121', 'Matriele vaste activa: Gronden en terreinen', 2, 'A1', 'A122',
                                     'Matriele vaste activa: Woonruimten', 2, 'A1', 'A123',
                                     'Matriele vaste activa: Bedrijfsgebouwen', 2, 'A1', 'A124',
                                     'Matriele vaste activa: Grond-, weg- en waterbouwkundige werken', 2, 'A1', 'A125',
                                     'Matriele vaste activa: Vervoermiddelen', 2, 'A1', 'A126',
                                     'Matriele vaste activa: Machines, apparaten en installaties', 2, 'A1', 'A129',
                                     'Matriele vaste activa: Overig', 2, 'A1', 'A1311',
                                     'Financiele vaste activa: Kapitaalverstrekking aan deelnemingen', 2, 'A1', 'A1312',
                                     'Financiele vaste activa: Kapitaalverstrekking aan gemeenschappelijke regelingen',
                                     2, 'A1', 'A1313',
                                     'Financiele vaste activa: Kapitaalverstrekking aan overige verbonden partijen', 2,
                                     'A1', 'A1321', 'Financiele vaste activa: Leningen aan woningbouwcorporaties', 2,
                                     'A1', 'A1322', 'Financiele vaste activa: Leningen aan deelnemingen', 2, 'A1',
                                     'A1323', 'Financiele vaste activa: Leningen aan overige verbonden partijen', 2,
                                     'A1', 'A1331a',
                                     'Financiele vaste activa: Leningen aan openbare lichamen (art. 1a Wet Fido)', 2,
                                     'A1', 'A1331b', 'Financiele vaste activa: Overige langlopende leningen', 2, 'A1',
                                     'A1332a',
                                     'Financiele vaste activa: Uitzettingen in s Rijks schatkist met een looptijd = 1 jaar',
                                     2, 'A1', 'A1332b',
                                     'Financiele vaste activa: Uitzettingen in de vorm van Nederlands schuldpapier met een looptijd = 1 jaar',
                                     2, 'A1', 'A1332c',
                                     'Financiele vaste activa: Overige uitzettingen met een looptijd = 1 jaar', 2, 'A1',
                                     'A2', 'Vlottende Activa', 1, '', 'A212',
                                     'Voorraden: Overige grond- en hulpstoffen', 2, 'A2', 'A213',
                                     'Voorraden: Onderhanden werk (incl. bouwgronden in exploitatie)', 2, 'A2', 'A214',
                                     'Voorraden: Gereed product en handelsgoederen', 2, 'A2', 'A215',
                                     'Voorraden: Vooruitbetalingen', 2, 'A2', 'A221',
                                     'Uitzettingen: Vorderingen op openbare lichamen', 2, 'A2', 'A222a',
                                     'Uitzettingen: Verstrekte kasgeldleningen aan openbare lichamen (art. 1a Wet Fido)',
                                     2, 'A2', 'A222b', 'Uitzettingen: Overige verstrekte kasgeldleningen', 2, 'A2',
                                     'A223a', 'Uitzettingen: Rekening courant verhouding met het Rijk', 2, 'A2',
                                     'A223b',
                                     'Uitzettingen: Rekening courant verhoudingen overige niet-Financiele instellingen',
                                     2, 'A2', 'A224', 'Uitzettingen: Overige vorderingen', 2, 'A2', 'A225a',
                                     'Uitzettingen: Uitzettingen in s Rijks schatkist met een looptijd < 1 jaar', 2,
                                     'A2', 'A225b',
                                     'Uitzettingen: Uitzettingen in de vorm van Nederlands schuldpapier met een looptijd < 1 jaar',
                                     2, 'A2', 'A225c', 'Uitzettingen: Overige uitzettingen met een looptijd < 1 jaar',
                                     2, 'A2', 'A23', 'Liquide middelen (kas- en banksaldi)', 2, 'A2', 'A29a',
                                     'Overlopende activa: Nog te ontvangen bijdragen van de EU', 2, 'A2', 'A29b',
                                     'Overlopende activa: Nog te ontvangen bijdragen van het Rijk', 2, 'A2', 'A29c',
                                     'Overlopende activa: Nog te ontvangen bijdragen van overige overheid', 2, 'A2',
                                     'A29d', 'Overlopende activa: Overige overlopende activa', 2, 'A2', 'P1',
                                     'Vaste Passiva', 1, '', 'P111', 'Eigen vermogen: Algemene reserve', 2, 'P1',
                                     'P112', 'Eigen vermogen: Bestemmingsreserves', 2, 'P1', 'P114',
                                     'Eigen vermogen: Saldo van rekening', 2, 'P1', 'P12', 'Voorzieningen', 2, 'P1',
                                     'P131', 'Vaste schuld: Obligatieleningen', 2, 'P1', 'P132',
                                     'Vaste schuld: Onderhandse leningen van binnenlandse pensioenfondsen en verzekeraars',
                                     2, 'P1', 'P133',
                                     'Vaste schuld: Onderhandse leningen van binnenlandse banken en overige Financiele instellingen',
                                     2, 'P1', 'P134', 'Vaste schuld: Onderhandse leningen van binnenlandse bedrijven',
                                     2, 'P1', 'P135a',
                                     'Vaste schuld: Onderhandse leningen van openbare lichamen (art. 1a Wet Fido)', 2,
                                     'P1', 'P135b',
                                     'Vaste schuld: Onderhandse leningen van overige binnenlandse sectoren', 2, 'P1',
                                     'P136', 'Vaste schuld: Onderhandse leningen van buitenlandse instellingen', 2,
                                     'P1', 'P137', 'Vaste schuld: Door derden belegde gelden', 2, 'P1', 'P138',
                                     'Vaste schuld: Waarborgsommen', 2, 'P1', 'P139', 'Renteswaps en derivaten', 2,
                                     'P1', 'P2', 'Vlottende Passiva', 1, '', 'P211a',
                                     'Vlottende schuld: Kasgeldleningen van openbare lichamen (art. 1a Wet Fido)', 2,
                                     'P2', 'P211b', 'Vlottende schuld: Overige kasgeldleningen', 2, 'P2', 'P212',
                                     'Vlottende schuld: Banksaldi', 2, 'P2', 'P213',
                                     'Vlottende schuld: Overige vlottende schulden', 2, 'P2', 'P29a',
                                     'Overlopende passiva: Vooruit ontvangen bijdragen van de EU', 2, 'P2', 'P29b',
                                     'Overlopende passiva: Vooruit ontvangen bijdragen van het Rijk', 2, 'P2', 'P29c',
                                     'Overlopende passiva: Vooruit ontvangen bijdragen van overige overheid', 2, 'P2',
                                     'P29d', 'Overlopende passiva: Overige overlopende passiva', 2, 'P2'],
                      'standper': ['1 januari', 'begindatum', 1, '', 'ultimo', 'einddatum', 1, ''],
                      'categorie_lasten': ['Lopende Rekening', '', 1, '', '1.1', 'Salarissen en sociale lasten', 2,
                                           'Lopende Rekening', '2.1', 'Belastingen', 2, 'Lopende Rekening', '3.1',
                                           'Grond', 2, 'Lopende Rekening', '3.2', 'Duurzame goederen', 2,
                                           'Lopende Rekening', '3.3', 'Pachten', 2, 'Lopende Rekening', '3.4.1',
                                           'Sociale uitkeringen in natura', 2, 'Lopende Rekening', '3.5.1',
                                           'Ingeleend personeel', 2, 'Lopende Rekening', '3.8',
                                           'Overige goederen en diensten', 2, 'Lopende Rekening', '4.1.1',
                                           'Sociale uitkeringen in geld', 2, 'Lopende Rekening', '4.2', 'Subsidies', 2,
                                           'Lopende Rekening', '4.3.1', 'Inkomensoverdrachten - Rijk', 2,
                                           'Lopende Rekening', '4.3.2', 'Inkomensoverdrachten - gemeenten', 2,
                                           'Lopende Rekening', '4.3.3',
                                           'Inkomensoverdrachten - gemeenschappelijke regelingen', 2,
                                           'Lopende Rekening', '4.3.4', 'Inkomensoverdrachten - provincies', 2,
                                           'Lopende Rekening', '4.3.5', 'Inkomensoverdrachten - waterschappen', 2,
                                           'Lopende Rekening', '4.3.6', 'Inkomensoverdrachten - overige overheden', 2,
                                           'Lopende Rekening', '4.3.7', 'Inkomensoverdrachten - Europese Unie', 2,
                                           'Lopende Rekening', '4.3.8',
                                           'Inkomensoverdrachten - overige instellingen en personen', 2,
                                           'Lopende Rekening', '4.3.9', 'Inkomensoverdrachten - onverdeeld', 2,
                                           'Lopende Rekening', '4.4.1', 'Kapitaaloverdrachten - Rijk', 2,
                                           'Lopende Rekening', '4.4.2', 'Kapitaaloverdrachten - gemeenten', 2,
                                           'Lopende Rekening', '4.4.3',
                                           'Kapitaaloverdrachten - gemeenschappelijke regelingen', 2,
                                           'Lopende Rekening', '4.4.4', 'Kapitaaloverdrachten - provincies', 2,
                                           'Lopende Rekening', '4.4.5', 'Kapitaaloverdrachten - waterschappen', 2,
                                           'Lopende Rekening', '4.4.6', 'Kapitaaloverdrachten - overige overheden', 2,
                                           'Lopende Rekening', '4.4.7', 'Kapitaaloverdrachten - Europese Unie', 2,
                                           'Lopende Rekening', '4.4.8',
                                           'Kapitaaloverdrachten - overige instellingen en personen', 2,
                                           'Lopende Rekening', '4.4.9', 'Kapitaaloverdrachten - onverdeeld', 2,
                                           'Lopende Rekening', '5.1', 'Rente', 2, 'Lopende Rekening',
                                           'Financiele Rekening', '', 1, '', '6.1', 'Financiele transacties', 2,
                                           'Financiele Rekening', 'Interne Verrekeningen', '', 1, '', '7.1',
                                           'Mutatie reserves', 2, 'Interne Verrekeningen', '7.2',
                                           'Mutatie voorzieningen', 2, 'Interne Verrekeningen', '7.3', 'Afschrijvingen',
                                           2, 'Interne Verrekeningen', '7.4', 'Toegerekende reeele en bespaarde rente',
                                           2, 'Interne Verrekeningen', '7.5', 'Overige verrekeningen', 2,
                                           'Interne Verrekeningen'],
                      'categorie_baten': ['Lopende Rekening', '', 1, '', '2.2.1', 'Belastingen op producenten', 2,
                                          'Lopende Rekening', '2.2.2', 'Belastingen op huishoudens', 2,
                                          'Lopende Rekening', '3.1', 'Grond', 2, 'Lopende Rekening', '3.2',
                                          'Duurzame goederen', 2, 'Lopende Rekening', '3.3', 'Pachten', 2,
                                          'Lopende Rekening', '3.4.2',
                                          'Eigen bijdragen en verhaal sociale uitkeringen in natura', 2,
                                          'Lopende Rekening', '3.5.2', 'Uitgeleend personeel', 2, 'Lopende Rekening',
                                          '3.6', 'Huren', 2, 'Lopende Rekening', '3.7', 'Leges en andere rechten', 2,
                                          'Lopende Rekening', '3.8', 'Overige goederen en diensten', 2,
                                          'Lopende Rekening', '4.1.2', 'Verhaal sociale uitkeringen in geld', 2,
                                          'Lopende Rekening', '4.3.1', 'Inkomensoverdrachten - Rijk', 2,
                                          'Lopende Rekening', '4.3.2', 'Inkomensoverdrachten - gemeenten', 2,
                                          'Lopende Rekening', '4.3.3',
                                          'Inkomensoverdrachten - gemeenschappelijke regelingen', 2, 'Lopende Rekening',
                                          '4.3.4', 'Inkomensoverdrachten - provincies', 2, 'Lopende Rekening', '4.3.5',
                                          'Inkomensoverdrachten - waterschappen', 2, 'Lopende Rekening', '4.3.6',
                                          'Inkomensoverdrachten - overige overheden', 2, 'Lopende Rekening', '4.3.7',
                                          'Inkomensoverdrachten - Europese Unie', 2, 'Lopende Rekening', '4.3.8',
                                          'Inkomensoverdrachten - overige instellingen en personen', 2,
                                          'Lopende Rekening', '4.3.9', 'Inkomensoverdrachten - onverdeeld', 2,
                                          'Lopende Rekening', '4.4.1', 'Kapitaaloverdrachten - Rijk', 2,
                                          'Lopende Rekening', '4.4.2', 'Kapitaaloverdrachten - gemeenten', 2,
                                          'Lopende Rekening', '4.4.3',
                                          'Kapitaaloverdrachten - gemeenschappelijke regelingen', 2, 'Lopende Rekening',
                                          '4.4.4', 'Kapitaaloverdrachten - provincies', 2, 'Lopende Rekening', '4.4.5',
                                          'Kapitaaloverdrachten - waterschappen', 2, 'Lopende Rekening', '4.4.6',
                                          'Kapitaaloverdrachten - overige overheden', 2, 'Lopende Rekening', '4.4.7',
                                          'Kapitaaloverdrachten - Europese Unie', 2, 'Lopende Rekening', '4.4.8',
                                          'Kapitaaloverdrachten - overige instellingen en personen', 2,
                                          'Lopende Rekening', '4.4.9', 'Kapitaaloverdrachten - onverdeeld', 2,
                                          'Lopende Rekening', '5.1', 'Rente', 2, 'Lopende Rekening', '5.2',
                                          'Dividenden en winsten', 2, 'Lopende Rekening', 'Financiele Rekening', '', 1,
                                          '', '6.1', 'Financiele transacties', 2, 'Financiele Rekening',
                                          'Interne Verrekeningen', '', 1, '', '7.1', 'Mutatie reserves', 2,
                                          'Interne Verrekeningen', '7.2', 'Mutatie voorzieningen', 2,
                                          'Interne Verrekeningen', '7.3', 'Afschrijvingen', 2, 'Interne Verrekeningen',
                                          '7.4', 'Toegerekende reeele en bespaarde rente', 2, 'Interne Verrekeningen',
                                          '7.5', 'Overige verrekeningen', 2, 'Interne Verrekeningen'],
                      'dimensies': ['dimensies_lasten', 'dimensies voor rekeningsoort lasten', 1, '', 'dimensie_1',
                                    'kolomkoppen lasten tabel', 2, 'dimensies_lasten', 'dimensie_2',
                                    'rijkoppen lasten tabel', 2, 'dimensies_lasten', 'dimensies_baten',
                                    'dimensies voor rekeningsoort baten', 1, '', 'dimensie_1',
                                    'kolomkoppen baten tabel', 2, 'dimensies_baten', 'dimensie_2',
                                    'rijkoppen baten tabel', 2, 'dimensies_baten', 'dimensies_balans_lasten',
                                    'dimensies voor rekeningsoort balans_lasten', 1, '', 'dimensie_1',
                                    'kolomkoppen balans_lasten tabel', 2, 'dimensies_balans_lasten', 'dimensie_2',
                                    'rijkoppen balans_lasten tabel', 2, 'dimensies_balans_lasten',
                                    'dimensies_balans_baten', 'dimensies voor rekeningsoort balans_baten', 1, '',
                                    'dimensie_1', 'kolomkoppen balans_baten tabel', 2, 'dimensies_balans_baten',
                                    'dimensie_2', 'rijkoppen balans_baten tabel', 2, 'dimensies_balans_baten',
                                    'dimensies_balans_standen', 'dimensies voor rekeningsoort balans_standen', 1, '',
                                    'dimensie_1', 'kolomkoppen balans_standen tabel', 2, 'dimensies_balans_standen',
                                    'dimensie_2', 'rijkoppen balans_standen tabel', 2, 'dimensies_balans_standen']}

        self.assertDictEqual(exp_result, result)

    def test_extract_values_from_json(self):
        from applicatie.logic.controles import extract_values_from_json